# Generated by Django 3.1.7 on 2021-03-31 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapters',
            new_name='Chapter',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
