# Generated by Django 3.1.7 on 2021-03-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210331_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='chapters',
            new_name='chapter',
        ),
    ]
